<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>Full</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Caching\Implementations\AppFabricCacheAdapter.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.8" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="PostSharp" Version="5.0.42" />
    <PackageReference Include="PostSharp.Patterns.Aggregation" Version="5.0.42" />
    <PackageReference Include="PostSharp.Patterns.Common" Version="5.0.42" />
    <PackageReference Include="PostSharp.Patterns.Model" Version="5.0.42" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Runtime.Caching" />
    <Reference Include="System.ServiceModel">
      <HintPath>..\..\..\..\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.ServiceModel.dll</HintPath>
    </Reference>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>